Repository wavesplatform/waves-documentation, pull requests merged in 2018-04, with the labels that each got.

#52 Websocket API
  proposals/websocket_api.md
Labels: enhancement, help wanted, wip

#73 NODE-651 Versioned transfer transaction
  application-development-and-api/waves-node-rest-api/asset-transactions/public-functions.md
  developers-guide/data-structures.md
Labels: enhancement

#84 Versioned transactions
  proposals/versioned_transactions.md
Labels: wip
